### ISSUE TITLE
Waiter WebApp

### ISSUE THREAD

**Issue by Gideon877** [Gideon877/waiter_webapp#1]
Hi
Please review my waiter_webapp readme and go through the installation steps to get my app running on your desktop.
If you have any comment or suggestion on how i could improve please let me know.

@LloMia
@Amandankosiyane
@lubba15
@viwesomagaca

Warm regards
Thabang

**Comment by Amandankosiyane** [comment]
Hi Thabang i followed all instructions to run your application but one of your tests is failing please check it out. And another thing i would like to see the admin side maybe if you could show us a route for your admin page. Other than that your application is working perfectly fine.



Amanda

**Comment by Gideon877** [comment]
Thank you very much @Amandankosiyane for the feedback. I fix the test error. And if u want to see the admin, you have to first register using this username  'admin'  and enter your own password, them navigate to .../days route.

**Comment by Amandankosiyane** [comment]
Hi @Gideon877  great work i retried again and now the application is working fine. I also love the progress bars.


Amanda
